In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
import pandas as pd

df = pd.read_csv(r'../data/processed/cleaned_dataset.csv')

# 1. **EDA**.

# **A. Check basic information again**

In [4]:
print(df.shape)
df.info()
df.describe()

(3025, 22)
<class 'pandas.DataFrame'>
RangeIndex: 3025 entries, 0 to 3024
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Post_ID                       3025 non-null   str
 1   Timestamp                     3025 non-null   str
 2   Platform                      3025 non-null   str
 3   Content_Type                  3025 non-null   str
 4   Category                      3025 non-null   str
 5   Likes                         3025 non-null   int64
 6   Comments                      3025 non-null   int64
 7   Shares                        3025 non-null   int64
 8   Views                         3025 non-null   int64
 9   Saves                         3025 non-null   int64
 10  Follower_Count                3025 non-null   int64
 11  Engagement_Rate               3025 non-null   float64
 12  Hour_of_Day                   3025 non-null   int64
 13  Day_of_Week                   3025 non-null   str
 14  Hashtag_Count                 3025 non-null   int64
 15  Content_Length                3025 non-null   int64
 16  Sentiment                     3025 non-null   str
 17  Influencer_Tier               3025 non-null   str
 18  Has_Media                     3025 non-null   bool
 19  Is_Verified                   3025 non-null   bool
 20  Flag_Engagement_Above_Views   3025 non-null   bool
 21  Flag_Engagement_Rate_Outlier  3025 non-null   bool
dtypes: bool(4), float64(1), int64(9), str(8)
memory usage: 437.3 KB

,Likes,Comments,Shares,Views,Saves,Follower_Count,Engagement_Rate,Hour_of_Day,Hashtag_Count,Content_Length
count,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.00000,3025.000000,3025.000000,3025.000000,3025.000000
mean,9910.899174,422.275041,851.301818,86901.163306,742.953058,247475.62281,16.258522,11.510083,14.532893,657.365950
std,11944.962957,462.769564,1210.354518,121208.993566,683.684526,144998.87731,90.214362,6.919223,8.668669,548.272956
min,35.000000,3.000000,2.000000,551.000000,8.000000,543.00000,0.060000,0.000000,0.000000,15.000000
25%,2914.000000,137.000000,138.000000,19576.000000,296.000000,122702.00000,1.420000,5.000000,7.000000,236.000000
50%,5739.000000,273.000000,280.000000,38651.000000,558.000000,242641.00000,3.010000,12.000000,15.000000,465.000000
75%,9047.000000,435.000000,870.000000,72320.000000,868.000000,373219.00000,8.520000,18.000000,22.000000,1021.000000
max,49949.000000,1999.000000,4997.000000,497812.000000,2999.000000,499815.00000,3510.460000,23.000000,29.000000,1999.000000

# **B. Analyze the platforms**

In [5]:
df["Platform"].value_counts()

Platform
Instagram    1283
Facebook      984
TikTok        758
Name: count, dtype: int64

# **C. Analyze engagement**

In [6]:
df[["Likes", "Comments", "Shares", "Views", "Saves", "Engagement_Rate"]].describe()

,Likes,Comments,Shares,Views,Saves,Engagement_Rate
count,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000,3025.000000
mean,9910.899174,422.275041,851.301818,86901.163306,742.953058,16.258522
std,11944.962957,462.769564,1210.354518,121208.993566,683.684526,90.214362
min,35.000000,3.000000,2.000000,551.000000,8.000000,0.060000
25%,2914.000000,137.000000,138.000000,19576.000000,296.000000,1.420000
50%,5739.000000,273.000000,280.000000,38651.000000,558.000000,3.010000
75%,9047.000000,435.000000,870.000000,72320.000000,868.000000,8.520000
max,49949.000000,1999.000000,4997.000000,497812.000000,2999.000000,3510.460000

# **D. Analyze content type**

In [7]:
df.groupby("Content_Type")["Engagement_Rate"].mean().sort_values(ascending=False)

Content_Type
Stitch      45.382664
Duet        41.630242
Video       22.608184
Reel        11.674739
Post        10.323583
Carousel     8.376246
Photo        6.283531
Story        5.924190
Live         5.494310
Name: Engagement_Rate, dtype: float64

# **E. Analyze posting time**

In [8]:
df.groupby("Hour_of_Day")["Engagement_Rate"].mean()

Hour_of_Day
0     22.401951
1     20.636642
2     16.671607
3      7.553083
4     14.815606
5     12.126202
6     10.157385
7     33.415304
8     39.347705
9     15.274297
10    12.391450
11    11.486579
12     6.817840
13    16.899612
14    13.709098
15    12.318696
16    18.177815
17    10.998992
18    23.188496
19    11.014355
20    28.488344
21    10.316812
22     8.070153
23    16.141068
Name: Engagement_Rate, dtype: float64

# **F. Analyze hashtags**

In [9]:
df.groupby("Hashtag_Count")["Engagement_Rate"].mean()

Hashtag_Count
0      9.980841
1     14.164706
2      7.757528
3     29.803100
4      5.602000
5     11.223097
6     27.166449
7     45.532909
8     12.890588
9     14.946796
10    14.368273
11    34.398557
12     8.632267
13    13.358750
14    17.317426
15    10.639802
16     9.237374
17     9.638989
18    13.383131
19    12.321414
20    11.618073
21    11.029145
22    13.738700
23    16.325714
24    12.769515
25    18.290948
26    21.449588
27     7.617000
28    23.953818
29    22.879444
Name: Engagement_Rate, dtype: float64